version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: btm_user
      POSTGRES_PASSWORD: btm_secret_2024
      POSTGRES_DB: beyond_the_music
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
