
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// NOT: datasource.url burada tanımlanmaz — schema.prisma içindeki
// `url = env("DATABASE_URL")` lazy olarak çözülür, böylece
// `prisma generate` (DB'ye ihtiyaç duymaz) env var olmadan da
// çalışabilir (örn. Vercel postinstall).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
});
